## Make a cleaner DataFrame with as much detail as useful

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
# The Before version, takes several secs to load (300+ MB)
df = pd.read_csv('bigframe.csv')
df.head()

,Unnamed: 0,checkin_id,beer.bid,user.uid,rating_score,brewery.brewery_name,beer.beer_name,beer.beer_style,brewery.brewery_id,brewery.brewery_type,...,venue.location.venue_country,venue.location.venue_state,venue.primary_category,venue.venue_id,checkin_comment,created_at,venue.type,beer.rating_score,beer.beer_description,abv
0,0,821797539,2095023,3340203,3.75,Stone Brewing,Stone Scorpion Bowl IPA,IPA - American,1204,Regional Brewery,...,NaN,NaN,NaN,NaN,"Easy-drinking, not too hoppy. Solid.","Sat, 26 Oct 2019 03:52:50 +0000",[],3.73789,To create a recipe so tropical and fruity with...,7.5
1,219,818949121,1709568,3340203,3.50,Ritual Brewing Company,Pale Ale,Pale Ale - American,39329,Micro Brewery,...,United States,CA,Nightlife Spot,376422.0,Solid.,"Sat, 19 Oct 2019 03:07:43 +0000",['brewery'],3.43165,NaN,5.2
2,221,818856642,2734572,3340203,4.25,Ritual Brewing Company,Oil Rig,IPA - Imperial / Double,39329,Micro Brewery,...,United States,CA,Nightlife Spot,376422.0,Gooood stuff. Cool place too.,"Sat, 19 Oct 2019 00:37:37 +0000",['brewery'],3.87873,NEW TRADITIONS CALL FOR NEW HOLIDAYS AND NEW H...,9.0
3,226,815159720,1044097,3340203,4.25,Stone Brewing,Stone Ruination Double IPA 2.0,IPA - Imperial / Double,1204,Regional Brewery,...,NaN,NaN,NaN,NaN,Probably the best Stone beer I’ve had. I’m a fan.,"Thu, 10 Oct 2019 02:20:55 +0000",[],4.01290,Stone Ruination IPA was the first full-time br...,8.5
4,331,814916483,1070,3340203,3.75,Lagunitas Brewing Company,Imperial Stout,Stout - Russian Imperial,765,Macro Brewery,...,NaN,NaN,NaN,NaN,"A really nice, if unspectacular, stout.","Wed, 09 Oct 2019 04:25:53 +0000",[],3.91420,"Made with Highly roasted malted barley, and pl...",9.9

In [3]:
df.shape

(1571140, 28)

In [4]:
df.columns

Index(['Unnamed: 0', 'checkin_id', 'beer.bid', 'user.uid', 'rating_score',
       'brewery.brewery_name', 'beer.beer_name', 'beer.beer_style',
       'brewery.brewery_id', 'brewery.brewery_type', 'brewery.country_name',
       'brewery.location.brewery_city', 'brewery.location.brewery_state',
       'brewery.location.lat', 'brewery.location.lng', 'venue.location.lat',
       'venue.location.lng', 'venue.location.venue_city',
       'venue.location.venue_country', 'venue.location.venue_state',
       'venue.primary_category', 'venue.venue_id', 'checkin_comment',
       'created_at', 'venue.type', 'beer.rating_score',
       'beer.beer_description', 'abv'],
      dtype='object')

In [5]:
# get rid of that first, useless column
df = df[df.columns[1:]]
# and rename a bunch of them
df.rename(columns={'beer.bid':'beer_id', 'user.uid':'user_id', 'rating_score':'rating_user',
       'brewery.brewery_name':'brewery_name', 'beer.beer_name':'beer_name', 
       'beer.beer_style':'beer_style', 'brewery.brewery_id':'brewery_id',
       'brewery.brewery_type':'brewery_type', 'brewery.country_name':'brewery_country',
       'brewery.location.brewery_city':'brewery_city',
       'brewery.location.brewery_state':'brewery_state',
       'brewery.location.lat':'brewery_lat', 'brewery.location.lng':'brewery_lon',
       'venue.location.lat':'venue_lat', 'venue.location.lng':'venue_lon',
       'venue.location.venue_city':'venue_city',
       'venue.location.venue_country':'venue_country',
       'venue.location.venue_state':'venue_state',
       'venue.primary_category':'venue_cat', 'venue.venue_id':'venue_id',
       'beer.rating_score':'rating_global',
       'beer.beer_description':'beer_description'},
        inplace=True)

In [6]:
df.columns

Index(['checkin_id', 'beer_id', 'user_id', 'rating_user', 'brewery_name',
       'beer_name', 'beer_style', 'brewery_id', 'brewery_type',
       'brewery_country', 'brewery_city', 'brewery_state', 'brewery_lat',
       'brewery_lon', 'venue_lat', 'venue_lon', 'venue_city', 'venue_country',
       'venue_state', 'venue_cat', 'venue_id', 'checkin_comment', 'created_at',
       'venue.type', 'rating_global', 'beer_description', 'abv'],
      dtype='object')

In [7]:
# missed one dot
df.rename(columns={'venue.type':'venue_type'},
        inplace=True)
df.columns

Index(['checkin_id', 'beer_id', 'user_id', 'rating_user', 'brewery_name',
       'beer_name', 'beer_style', 'brewery_id', 'brewery_type',
       'brewery_country', 'brewery_city', 'brewery_state', 'brewery_lat',
       'brewery_lon', 'venue_lat', 'venue_lon', 'venue_city', 'venue_country',
       'venue_state', 'venue_cat', 'venue_id', 'checkin_comment', 'created_at',
       'venue_type', 'rating_global', 'beer_description', 'abv'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1571140 entries, 0 to 1571139
Data columns (total 27 columns):
checkin_id          1571140 non-null int64
beer_id             1571140 non-null int64
user_id             1571140 non-null int64
rating_user         1571140 non-null float64
brewery_name        1571140 non-null object
beer_name           1571140 non-null object
beer_style          1571140 non-null object
brewery_id          1571140 non-null int64
brewery_type        1571140 non-null object
brewery_country     1571140 non-null object
brewery_city        1554436 non-null object
brewery_state       1546325 non-null object
brewery_lat         1571140 non-null float64
brewery_lon         1571140 non-null float64
venue_lat           1101509 non-null float64
venue_lon           1101509 non-null float64
venue_city          1052604 non-null object
venue_country       1101367 non-null object
venue_state         1087951 non-null object
venue_cat           1092671 non-null object
venue_id            1101509 non-null float64
checkin_comment     343881 non-null object
created_at          1571140 non-null object
venue_type          1571140 non-null object
rating_global       1334805 non-null float64
beer_description    1163702 non-null object
abv                 1571140 non-null float64
dtypes: float64(8), int64(4), object(15)
memory usage: 323.6+ MB

In [9]:
df.head()

,checkin_id,beer_id,user_id,rating_user,brewery_name,beer_name,beer_style,brewery_id,brewery_type,brewery_country,...,venue_country,venue_state,venue_cat,venue_id,checkin_comment,created_at,venue_type,rating_global,beer_description,abv
0,821797539,2095023,3340203,3.75,Stone Brewing,Stone Scorpion Bowl IPA,IPA - American,1204,Regional Brewery,United States,...,NaN,NaN,NaN,NaN,"Easy-drinking, not too hoppy. Solid.","Sat, 26 Oct 2019 03:52:50 +0000",[],3.73789,To create a recipe so tropical and fruity with...,7.5
1,818949121,1709568,3340203,3.50,Ritual Brewing Company,Pale Ale,Pale Ale - American,39329,Micro Brewery,United States,...,United States,CA,Nightlife Spot,376422.0,Solid.,"Sat, 19 Oct 2019 03:07:43 +0000",['brewery'],3.43165,NaN,5.2
2,818856642,2734572,3340203,4.25,Ritual Brewing Company,Oil Rig,IPA - Imperial / Double,39329,Micro Brewery,United States,...,United States,CA,Nightlife Spot,376422.0,Gooood stuff. Cool place too.,"Sat, 19 Oct 2019 00:37:37 +0000",['brewery'],3.87873,NEW TRADITIONS CALL FOR NEW HOLIDAYS AND NEW H...,9.0
3,815159720,1044097,3340203,4.25,Stone Brewing,Stone Ruination Double IPA 2.0,IPA - Imperial / Double,1204,Regional Brewery,United States,...,NaN,NaN,NaN,NaN,Probably the best Stone beer I’ve had. I’m a fan.,"Thu, 10 Oct 2019 02:20:55 +0000",[],4.01290,Stone Ruination IPA was the first full-time br...,8.5
4,814916483,1070,3340203,3.75,Lagunitas Brewing Company,Imperial Stout,Stout - Russian Imperial,765,Macro Brewery,United States,...,NaN,NaN,NaN,NaN,"A really nice, if unspectacular, stout.","Wed, 09 Oct 2019 04:25:53 +0000",[],3.91420,"Made with Highly roasted malted barley, and pl...",9.9

In [2]:
bdf = pd.read_csv('bigBeerFrame.csv')

In [3]:
bdf.columns

Index(['Unnamed: 0', 'checkin_id', 'date', 'checkin_comment', 'rating_user',
       'user_id', 'venue_lat', 'venue_lon', 'venue_city', 'venue_state',
       'venue_country', 'venue_cat', 'venue_type', 'venue_id', 'beer_id',
       'beer_name', 'abv', 'description', 'beer_style', 'rating_global',
       'brewery_id', 'brewery_name', 'brewery_type', 'brewery_country',
       'brewery_city', 'brewery_state', 'brewery_lat', 'brewery_lon'],
      dtype='object')

In [4]:
bdf = bdf[bdf.columns[1:]]

In [6]:
print(bdf.date[0], type(bdf.date[0]))

Sat, 21 Dec 2019 05:52:07 +0000 <class 'str'>

In [8]:
# convert those stringy dates to datetimes
# This took a few minutes
date = pd.to_datetime(bdf['date'])

In [9]:
bdf['date'] = date
bdf.date[:11]

0    2019-12-21 05:52:07+00:00
1    2019-12-20 04:26:42+00:00
2    2019-12-20 02:52:06+00:00
3    2019-12-03 21:53:09+00:00
4    2019-12-01 21:53:24+00:00
5    2019-11-25 04:32:51+00:00
6    2019-11-09 20:51:55+00:00
7    2019-09-27 19:37:58+00:00
8    2019-07-17 22:56:21+00:00
9    2019-06-29 16:16:31+00:00
10   2019-05-18 02:19:08+00:00
Name: date, dtype: datetime64[ns, UTC]

## Remove the checkins with no user rating, for the purposes of this project.

In [10]:
df = df[df.rating_user > 0]
df.shape

(1425447, 27)

In [11]:
print(f'User ratings range from {min(df.rating_user)} to {max(df.rating_user)}')

User ratings range from 0.25 to 5.0

In [10]:
print(bdf.shape)
bdf = bdf[bdf.rating_user > 0]
print(bdf.shape)

(692291, 27)
(636518, 27)

### See what the brewery columns look like

In [12]:
df.loc[:30, 'brewery_id':'brewery_lon']

,brewery_id,brewery_type,brewery_country,brewery_city,brewery_state,brewery_lat,brewery_lon
0,1204,Regional Brewery,United States,Escondido,CA,33.1157,-117.1200
1,39329,Micro Brewery,United States,Redlands,CA,34.0708,-117.2370
2,39329,Micro Brewery,United States,Redlands,CA,34.0708,-117.2370
3,1204,Regional Brewery,United States,Escondido,CA,33.1157,-117.1200
4,765,Macro Brewery,United States,Petaluma,CA,38.2724,-122.6620
5,1534,Regional Brewery,United States,Carlsbad,CA,33.1596,-117.3480
6,68356,Regional Brewery,United States,San Diego,CA,32.7542,-117.2060
7,908,Regional Brewery,United States,Holland,MI,42.8182,-86.1143
8,1620,Cidery,United States,Julian,CA,33.0978,-116.6470
9,1620,Cidery,United States,Julian,CA,33.0978,-116.6470
10,1620,Cidery,United States,Julian,CA,33.0978,-116.6470
11,1204,Regional Brewery,United States,Escondido,CA,33.1157,-117.1200
12,404,Regional Brewery,United States,San Diego,CA,32.7719,-117.2050
13,1142,Regional Brewery,United States,Chico,CA,39.7242,-121.8150
14,60062,Micro Brewery,United States,San Diego,CA,32.8805,-117.1630
15,1613,Micro Brewery,United States,Eugene,OR,44.0582,-123.1070
16,524,Regional Brewery,United States,Paso Robles,CA,35.5953,-120.6940
17,24,Regional Brewery,United States,Portland,ME,43.7028,-70.3182
18,400207,Nano Brewery,United States,Richmond,VA,37.6158,-77.6526
19,16167,Micro Brewery,United States,Richmond,VA,37.5637,-77.4603
20,16167,Micro Brewery,United States,Richmond,VA,37.5637,-77.4603
21,16167,Micro Brewery,United States,Richmond,VA,37.5637,-77.4603
22,16167,Micro Brewery,United States,Richmond,VA,37.5637,-77.4603
23,16167,Micro Brewery,United States,Richmond,VA,37.5637,-77.4603
24,249,Regional Brewery,United States,Cooperstown,NY,42.6818,-74.9255
25,44719,Micro Brewery,United States,Ashland,VA,37.7228,-77.4467
26,22526,Regional Brewery,United States,Vista,CA,33.1363,-117.2240
27,1204,Regional Brewery,United States,Escondido,CA,33.1157,-117.1200
28,4406,Micro Brewery,United States,Los Angeles,CA,34.0466,-118.2380
29,35865,Micro Brewery,United States,Claremont,CA,34.1090,-117.7020
30,3287,Regional Brewery,United States,Redlands,CA,34.0831,-117.1420

### Check the venue columns

In [13]:
df.loc[:30, 'venue_lat':'venue_id']

,venue_lat,venue_lon,venue_city,venue_country,venue_state,venue_cat,venue_id
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,34.0707,-117.2370,Redlands,United States,CA,Nightlife Spot,376422.0
2,34.0707,-117.2370,Redlands,United States,CA,Nightlife Spot,376422.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,34.0549,-116.9650,NaN,United States,CA,Food,4177151.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,32.7353,-117.1490,San Diego,United States,CA,Arts & Entertainment,21664.0
12,32.8680,-117.2330,La Jolla,United States,CA,Food,5701181.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,33.7997,-117.8830,Anaheim,United States,CA,Arts & Entertainment,114.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,38.9748,-77.0120,Takoma Park,United States,MD,Food,163567.0
18,37.6155,-77.6519,Richmond,United States,VA,Nightlife Spot,7441724.0
19,37.6155,-77.6519,Richmond,United States,VA,Nightlife Spot,7441724.0
20,37.6155,-77.6519,Richmond,United States,VA,Nightlife Spot,7441724.0
21,37.6155,-77.6519,Richmond,United States,VA,Nightlife Spot,7441724.0
22,37.6155,-77.6519,Richmond,United States,VA,Nightlife Spot,7441724.0
23,37.6155,-77.6519,Richmond,United States,VA,Nightlife Spot,7441724.0
24,37.5669,-77.4681,Richmond,United States,VA,Food,4168330.0
25,37.6096,-77.5182,Henrico County,United States,VA,Food,1723298.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,34.0565,-118.2490,Los Angeles,United States,CA,Arts & Entertainment,7966675.0
29,32.7477,-117.1290,San Diego,United States,CA,Nightlife Spot,4646289.0
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## And the rest of the columns

In [14]:
df.loc[:30, 'checkin_comment':]

,checkin_comment,created_at,venue_type,rating_global,beer_description,abv
0,"Easy-drinking, not too hoppy. Solid.","Sat, 26 Oct 2019 03:52:50 +0000",[],3.73789,To create a recipe so tropical and fruity with...,7.50
1,Solid.,"Sat, 19 Oct 2019 03:07:43 +0000",['brewery'],3.43165,NaN,5.20
2,Gooood stuff. Cool place too.,"Sat, 19 Oct 2019 00:37:37 +0000",['brewery'],3.87873,NEW TRADITIONS CALL FOR NEW HOLIDAYS AND NEW H...,9.00
3,Probably the best Stone beer I’ve had. I’m a fan.,"Thu, 10 Oct 2019 02:20:55 +0000",[],4.01290,Stone Ruination IPA was the first full-time br...,8.50
4,"A really nice, if unspectacular, stout.","Wed, 09 Oct 2019 04:25:53 +0000",[],3.91420,"Made with Highly roasted malted barley, and pl...",9.90
5,Can’t believe it took me this long to try this...,"Sat, 05 Oct 2019 00:54:32 +0000",[],3.84851,Note: Swami's IPA is brewed and distributed fr...,6.80
6,Damn good.,"Sat, 14 Sep 2019 22:48:11 +0000",['steakhouse'],4.00465,This deeply juicy stunner in the mold of City ...,6.70
7,MMMmmmmMmmmmmm.,"Thu, 05 Sep 2019 02:44:18 +0000",[],4.06110,A stout with roasty malt character intermingle...,11.00
8,"A nice, easy-drinking cider.","Mon, 02 Sep 2019 04:47:27 +0000",[],3.36631,Julian Harvest Apple Cider is lightly carbonat...,6.99
9,Also bomb. Delayed check-in here.,"Mon, 02 Sep 2019 04:44:11 +0000",[],3.67697,Refreshing raspberry cider. Tart and fruity,6.99
10,This shit is BOMB.,"Mon, 02 Sep 2019 04:42:34 +0000",[],3.69683,Get ready to rumble with our new Julian Hard C...,6.99
11,No too shabby. Hoppy for sure but not to much ...,"Sat, 31 Aug 2019 21:51:10 +0000","['zoo', 'park']",3.75542,Red India Pale Ale w/ Pommegranate made by Pin...,7.50
12,A decent IPA if you’re into guava.,"Sat, 31 Aug 2019 19:34:17 +0000","['sandwich_place', 'salad_place', 'shopping_ma...",3.67951,Tropical fruit meets tropical vibes in this “g...,7.00
13,Fresh and tasty.,"Mon, 19 Aug 2019 02:15:17 +0000",[],3.79729,"As brewers, we get the privilege to sample our...",6.70
14,Damn good.,"Sun, 18 Aug 2019 03:25:00 +0000",[],3.99881,NaN,9.00
15,Really enjoyed this.,"Wed, 31 Jul 2019 02:28:29 +0000",['baseball_stadium'],3.73392,"Munich malt, 4 different hops and grapefruit p...",6.50
16,Lucked into this after a buddy aged it for thr...,"Tue, 30 Jul 2019 00:38:50 +0000",[],4.40299,Brewed with Belgian candi sugar and aged in a ...,11.60
17,Always good.,"Mon, 22 Jul 2019 00:26:53 +0000","['american_restaurant', 'korean_restaurant', '...",3.76062,Allagash White features a refreshing balance o...,5.20
18,Not bad.,"Fri, 19 Jul 2019 01:16:11 +0000",['brewery'],3.39232,"A cold conditioned sparkling ale, Tangerine Su...",4.20
19,Not too bad.,"Fri, 19 Jul 2019 00:57:03 +0000",['brewery'],NaN,NaN,5.00
20,Niiiiiiiiice.,"Fri, 19 Jul 2019 00:41:52 +0000",['brewery'],4.03611,Hardywood Bourbon Cru is brewed in the fashion...,12.00
21,"I’m eh on creams, and this didn’t do anything ...","Fri, 19 Jul 2019 00:14:16 +0000",['brewery'],3.33346,"In 1935, Richmond, Virginia made beer history ...",4.40
22,"Super citrusy, easy-to-drink IPA. I’m a fan.","Fri, 19 Jul 2019 00:05:51 +0000",['brewery'],3.76000,New England-Style IPA w/ Guava,7.50
23,What a nice sour.,"Thu, 18 Jul 2019 23:59:59 +0000",['brewery'],NaN,NaN,3.60
24,I am a fan.,"Thu, 18 Jul 2019 18:14:43 +0000","['burger_joint', 'beer_garden']",3.81542,"Gently tart, delicately sweet and completely r...",6.90
25,"A nice hoppy, green IPA. Great with barbecue.","Wed, 17 Jul 2019 18:16:59 +0000",['bbq_joint'],3.74701,Pocahoptas is a hop forward India Pale Ale tha...,6.80
26,Pretty good. Easy to drink as far as IPAs go.,"Sun, 07 Jul 2019 03:27:26 +0000",[],3.88625,On our relentless pursuit to bring the world u...,7.20
27,Good summer beer.,"Sat, 06 Jul 2019 04:23:08 +0000",[],3.59832,Imagine you set sail for a three hour tour. Le...,5.80
28,A really solid IPA.,"Sun, 23 Jun 2019 03:29:12 +0000",['concert_hall'],3.56930,"Angel City IPA is a medium-bodied, copper-hued...",6.10
29,Good stuff here.,"Thu, 20 Jun 2019 00:17:42 +0000",['beer_bar'],3.82279,hazy IPA,7.00
30,NaN,"Sat, 15 Jun 2019 22:10:52 +0000",[],3.74983,Betty is an American IPA boasting a blend of M...,6.50

In [15]:
# What percent of abv's are listed?
print(f'Percent of beers whose a.b.v. is listed: {sum(df.abv > 0) * 100 / df.shape[0]}')
print()
# What percent of beers have a description?
print(f'Percent of beers with a description: {100 - sum(df.beer_description.isnull()) * 100 / df.shape[0]}')
print()
# What percent have a global rating?
print(f'Percent of beers with a global rating: {sum(df.rating_global > 0) * 100 / df.shape[0]}')

Percent of beers whose a.b.v. is listed: 98.89227729968214

Percent of beers with a description: 74.22043751889758

Percent of beers with a global rating: 84.87681408007452

In [16]:
df.venue_type[:15]  # empty lists for NaN, and lists of varying length for the others

0                                                    []
1                                           ['brewery']
2                                           ['brewery']
3                                                    []
4                                                    []
5                                                    []
6                                        ['steakhouse']
7                                                    []
8                                                    []
9                                                    []
10                                                   []
11                                      ['zoo', 'park']
12    ['sandwich_place', 'salad_place', 'shopping_ma...
13                                                   []
14                                                   []
Name: venue_type, dtype: object

## Last column is the checkin timestamps, which appear to be strings still

In [17]:
print(df.created_at[0], type(df.created_at[0]))

Sat, 26 Oct 2019 03:52:50 +0000 <class 'str'>

In [18]:
# This took several minutes
date = pd.to_datetime(df['created_at'])

df['date'] = date

df.date[:20]

In [20]:
df.drop(columns=['created_at'], axis=1, inplace=True)
df.head()

,checkin_id,beer_id,user_id,rating_user,brewery_name,beer_name,beer_style,brewery_id,brewery_type,brewery_country,...,venue_country,venue_state,venue_cat,venue_id,checkin_comment,venue_type,rating_global,beer_description,abv,date
0,821797539,2095023,3340203,3.75,Stone Brewing,Stone Scorpion Bowl IPA,IPA - American,1204,Regional Brewery,United States,...,NaN,NaN,NaN,NaN,"Easy-drinking, not too hoppy. Solid.",[],3.73789,To create a recipe so tropical and fruity with...,7.5,2019-10-26 03:52:50+00:00
1,818949121,1709568,3340203,3.50,Ritual Brewing Company,Pale Ale,Pale Ale - American,39329,Micro Brewery,United States,...,United States,CA,Nightlife Spot,376422.0,Solid.,['brewery'],3.43165,NaN,5.2,2019-10-19 03:07:43+00:00
2,818856642,2734572,3340203,4.25,Ritual Brewing Company,Oil Rig,IPA - Imperial / Double,39329,Micro Brewery,United States,...,United States,CA,Nightlife Spot,376422.0,Gooood stuff. Cool place too.,['brewery'],3.87873,NEW TRADITIONS CALL FOR NEW HOLIDAYS AND NEW H...,9.0,2019-10-19 00:37:37+00:00
3,815159720,1044097,3340203,4.25,Stone Brewing,Stone Ruination Double IPA 2.0,IPA - Imperial / Double,1204,Regional Brewery,United States,...,NaN,NaN,NaN,NaN,Probably the best Stone beer I’ve had. I’m a fan.,[],4.01290,Stone Ruination IPA was the first full-time br...,8.5,2019-10-10 02:20:55+00:00
4,814916483,1070,3340203,3.75,Lagunitas Brewing Company,Imperial Stout,Stout - Russian Imperial,765,Macro Brewery,United States,...,NaN,NaN,NaN,NaN,"A really nice, if unspectacular, stout.",[],3.91420,"Made with Highly roasted malted barley, and pl...",9.9,2019-10-09 04:25:53+00:00

In [21]:
df.columns

Index(['checkin_id', 'beer_id', 'user_id', 'rating_user', 'brewery_name',
       'beer_name', 'beer_style', 'brewery_id', 'brewery_type',
       'brewery_country', 'brewery_city', 'brewery_state', 'brewery_lat',
       'brewery_lon', 'venue_lat', 'venue_lon', 'venue_city', 'venue_country',
       'venue_state', 'venue_cat', 'venue_id', 'checkin_comment', 'venue_type',
       'rating_global', 'beer_description', 'abv', 'date'],
      dtype='object')

In [22]:
# Should've added the index=False argument here, to keep datetimes and venue lists from being converted to strings
df.to_csv('bigframe.csv')

In [20]:
# make same column order for bdf  (can't just use df.columns since i don't want to reload df)
bdf = bdf[['checkin_id', 'beer_id', 'user_id', 'rating_user', 'brewery_name',
       'beer_name', 'beer_style', 'brewery_id', 'brewery_type',
       'brewery_country', 'brewery_city', 'brewery_state', 'brewery_lat',
       'brewery_lon', 'venue_lat', 'venue_lon', 'venue_city', 'venue_country',
       'venue_state', 'venue_cat', 'venue_id', 'checkin_comment', 'venue_type',
       'rating_global', 'description', 'abv', 'date']]

In [21]:
bdf.head()

,checkin_id,beer_id,user_id,rating_user,brewery_name,beer_name,beer_style,brewery_id,brewery_type,brewery_country,...,venue_country,venue_state,venue_cat,venue_id,checkin_comment,venue_type,rating_global,description,abv,date
0,843971771,526725,1373368,3.75,Wicks Brewing,Battle Cry IPA,IPA - American,44236,Brew Pub,United States,...,United States,CA,[],3966054.0,NaN,Nightlife Spot,3.63385,NaN,6.8,2019-12-21 05:52:07+00:00
1,843407973,526725,3484155,3.50,Wicks Brewing,Battle Cry IPA,IPA - American,44236,Brew Pub,United States,...,United States,CA,[],9586831.0,Brewed for the House.,Arts & Entertainment,3.63385,NaN,6.8,2019-12-20 04:26:42+00:00
2,843380508,526725,342359,4.00,Wicks Brewing,Battle Cry IPA,IPA - American,44236,Brew Pub,United States,...,United States,CA,[],3966054.0,NaN,Nightlife Spot,3.63385,NaN,6.8,2019-12-20 02:52:06+00:00
3,837180407,526725,6700685,4.50,Wicks Brewing,Battle Cry IPA,IPA - American,44236,Brew Pub,United States,...,NaN,NaN,[],NaN,NaN,NaN,3.63385,NaN,6.8,2019-12-03 21:53:09+00:00
4,836736462,526725,3094250,3.50,Wicks Brewing,Battle Cry IPA,IPA - American,44236,Brew Pub,United States,...,NaN,NaN,[],NaN,NaN,NaN,3.63385,NaN,6.8,2019-12-01 21:53:24+00:00

In [22]:
bdf.to_csv('bigBeerFrame.csv', index=False)